# - * - coding:utf8 - * - -
###########################################
# Author: Tinkle
# E-mail: shutingnjupt@gmail.com
# Name:  Find the Difference.py
# Creation Time: 2018/3/5
###########################################
'''
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
'''
class Solution(object):
	def findTheDifference(self, s, t):
		ret =0
		for x in s+t:
			ret = ord(x) ^ ret
		return chr(ret)